apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    name: apache
    tier: "FrontEnd"
    app: "apache"
    
spec:
  containers:
  - name: apache
    image: bitnami/apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80