apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    name: nginx-app

spec:
  containers:
  - name: nginx-app
    image: nginx:1.18.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

